
title: Sankhadip Roy # 
logo:  "/images/untitled%20(1).jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist and Educator with over a decade of experience, currently a Teaching Faculty in Mathematics and Statistics at the University of Massachusetts, Boston. 
  <br><br>
  Experienced in diverse data science projects, such as Time Series Forecasting, predictive modeling for insurance claims, and network analysis for social media data. 
  <br><br>
  Skilled in Python, R, and SQL, and proficient with algorithms including Linear and Logistic Regression, Random Forest, XGBOOST, Neural Networks, and time series modeling. Recognized for strong collaboration and teaching excellence in both academic and applied research settings.
  <br><br>
  <a href="https://www.linkedin.com/in/sankhadip-roy-93758631/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme


#theme: jekyll-theme-cayman
